# Generated by Django 3.0 on 2021-02-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recruitme'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitme',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
